kaltura/kms-automation

web/ini/testPartnersTestingNewUI.csv
web/lib/base.py
web/lib/myMedia.py
web/tests/basics/test_302.py

Fixed navigatet to URL (https)
Added try and except in tearDown method
Fixed getSearchBarElement for NEW UI

Switch to NEW UI

---

web/lib/myMedia.py

checkSingleEntryInMyMedia
clickActionsAndPublish
publishSingleEntryPrivacyToUnlisted

Publish as unlisted from my media:

---

web/lib/editEntryPage.py
web/lib/login.py
web/tests/basics/test_345.py

finished add addCollaborator function

add logout function

---

web/lib/editEntryPage.py
web/lib/login.py
web/lib/myMedia.py
web/tests/basics/test_345.py

start written changeEntryMetadata in EditEnrtyPage

start written publishSingleEntryInMyMedia in myMedia page

---

web/lib/category.py
web/lib/clsCommon.py
web/lib/myMedia.py
web/tests/basics/test_345.py

Finished publishSingleEntryInMyMedia

New Category class

---

web/lib/base.py
web/lib/category.py
web/lib/editEntryPage.py
web/lib/upload.py
web/tests/basics/test_345.py

clickOnEntryAfterSearchInCategory
get_child_elements_by_type
get_child_elements

New methods:

---

web/lib/admin.py
web/lib/base.py
web/lib/enums.py
web/lib/upload.py

wait_for_text
wait_visible
Admin module:
adminDisclaimer - Finished
Enum:
DisclaimerDisplayArea

Change to better timeout in next methods:

---

web/lib/category.py
web/lib/editEntryPage.py
web/lib/entryPage.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/basics/test_1555.py
web/tests/basics/test_345.py

New methods:
navigateToEntryPageFromCategoryPage
verifyEntryMetadata

Finished test 345 (Collaboration Co Edit)

---

web/lib/channel.py
web/lib/editEntryPage.py
web/tests/basics/test_883.py

1. searchAChannelInMyChannels
2. navigateToChannel
3. verifyIfSingleEntryInChannel
4. addPublishingSchedule

added new methods:

---

web/lib/clsTestService.py
web/lib/localSettings.py

Default download for FF and Chrome

---

web/lib/base.py
web/lib/clsBrowserMobCapture.py
web/lib/clsPractiTest.py
web/lib/clsTestService.py
web/lib/logger.py
web/lib/utilityTestFunc.py

REVERT to working version

---

web/lib/clsTestService.py

Clean folders only from local host.

---

web/ini/testPartnersTestingNewUI.csv

(admin: tzachi.guetta@kaltura.com;Kaltura1!)

New Partner for automation, 2370071.qakmstest.dev.kaltura.com

---

web/lib/editEntryPage.py
web/lib/enums.py
web/lib/player.py
web/tests/basics/test_351.py

verifySlidesInPlayerSideBar
changePlayerView
change function:
uploadSlidesDeck
added enum:
PlayerView

add functions:

---

web/ini/testPartnersTestingNewUI.csv
web/lib/base.py
web/lib/clsPractiTest.py
web/lib/clsTestService.py
web/lib/localSettings.py
web/lib/logger.py
web/tests/basics/test_1555.py
web/tests/basics/test_1556.py
web/tests/basics/test_1557.py
web/tests/basics/test_1594.py
web/tests/basics/test_16.py
web/tests/basics/test_2565.py
web/tests/basics/test_2566.py
web/tests/basics/test_2567.py
web/tests/basics/test_302.py
web/tests/basics/test_345.py
web/tests/basics/test_346.py
web/tests/basics/test_347.py
web/tests/basics/test_348.py
web/tests/basics/test_349.py
web/tests/basics/test_350.py
web/tests/basics/test_351.py
web/tests/basics/test_767.py
web/tests/basics/test_869.py
web/tests/basics/test_876.py
web/tests/basics/test_883.py

Refactor All Tests - add handleFail

---

web/lib/logger.py
web/lib/upload.py
web/tests/basics/test_346.py
web/tests/basics/test_347.py
web/tests/basics/test_348.py

Tests 346,347,348 - add 'test passed'
Log for remote in progress

Upload method - change to wait visible

---

web/lib/clsTestService.py
web/lib/upload.py
web/tests/basics/test_1555.py

added test id to add guid method

UPLOAD fix

---

web/lib/editEntryPage.py
web/tests/basics/test_348.py
web/tests/basics/test_353.py

started written test : Slide Deck Upload - add chapters

---

web/lib/editEntryPage.py
web/lib/entryPage.py
web/lib/myMedia.py
web/lib/player.py
web/tests/basics/test_345.py
web/tests/basics/test_353.py

finish test 353

---

web/ini/testPartnersTestingNewUI.csv
web/lib/myMedia.py
web/tests/basics/test_894.py

added isEntryPresented

---

web/lib/player.py
web/tests/basics/test_353.py

Test entry name fix

---

web/lib/base.py
web/lib/editEntryPage.py
web/lib/localSettings.py
web/lib/myMedia.py
web/lib/upload.py

Changed default LOCAL_SETTINGS_RUN_MDOE = LOCAL_RUN_MODE

Added Retries for Upload method

---

web/lib/base.py
web/lib/channel.py
web/lib/myMedia.py

Changed 'MY_CHANNELS_SERACH_FIELD' for old ui also

Send keys with multipleElements

---

web/lib/base.py
web/lib/clsQrCodeReader.py
web/lib/upload.py

Fixed takeQrCodeSlideScreenshot

Added try/catch to clickElement

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/category.py
web/lib/clsCommon.py
web/lib/clsTestService.py
web/lib/enums.py
web/lib/upload.py
web/tests/basics/test_706.py

Tests 706 done
Upload method updated

Added navigateTo generic method

---

web/lib/base.py
web/lib/upload.py

New Infrastructure methods:
wait_visible_child
wait_for_child_text
click_child
send_keys_to_child
get_element_child_text
New infra for Multiple Upload:
uploadMulitple
fillFileUploadEntryDetailsMultiple
Handle tags in Chrome:
Remove the Mask over all the screen (over tags filed also), before send keys

New Object: UploadEntry()

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/lib/player.py
web/tests/basics/test_3273.py
web/tests/basics/test_3274.py
web/tests/basics/test_3275.py
web/tests/basics/test_3276.py

cange test id to much practitest

fix test 3275

---

web/lib/editEntryPage.py
web/lib/entryPage.py
web/lib/player.py
web/tests/basics/test_3283.py

add function verifySlidesInTimeLine

finish tedt 3283 - Slide Deck Upload- A-sync upload for new+old UI

---

web/lib/player.py
web/tests/uploadSlideDeck/test_3275.py
web/tests/uploadSlideDeck/test_3284.py

almost finished test 3284 - Slide Deck Upload- search slides

added function searchSlideInSlidesBarMenu

---

web/lib/base.py
web/lib/editEntryPage.py

add multipleElements to wait_visible

base methods updated

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/entryPage.py
web/tests/entryPage/test_687.py
web/tests/myHistory/test_2742.py
web/tests/playlist/test_673.py

Converted tests: #673, 687.

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/category.py
web/lib/entryPage.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/channel/converted/test_734.py

started test 734 - channel entry details

finished test 709 - category entry details for NEW UI

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/base.py
web/lib/category.py
web/lib/channel.py
web/tests/category/converted/.pytest_cache/v/cache/nodeids
web/tests/category/converted/test_709.py
web/tests/channel/converted/.pytest_cache/v/cache/nodeids
web/tests/channel/converted/test_731.py

started test 731 - Channel page information

test 709, 734 - fixed to work with old UI

---

web/lib/base.py
web/lib/clsCommon.py
web/lib/editEntryPage.py

Added leavePageExpected to handleTestFail

---

web/lib/channel.py
web/lib/player.py
web/tests/channel/converted/test_731.py
web/tests/editEntryPage/thumbnail/.pytest_cache/v/cache/nodeids
web/tests/uploadSlideDeck/.pytest_cache/v/cache/nodeids
web/tests/uploadSlideDeck/test_3275.py

fix test 731 - channel page information to work with old ui

fix bugs in test 3275

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/tests/MyMedia/converted/test_665.py
web/tests/channel/converted/.pytest_cache/v/cache/nodeids
web/tests/channel/converted/test_728.py
web/tests/channel/converted/test_731.py

started test 728 - My Channels - Search as member - NOT FINISHED

finished test 665 - sreach in my media for old ui

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/tests/channel/converted/.pytest_cache/v/cache/nodeids
web/tests/channel/converted/test_727.py
web/tests/channel/converted/test_729.py

finished test 727 - My Channels - Search as manager for old /new ui
finished test 729 - My Channels - Search as subscriber for old /new ui

finished test 728 - My Channels - Search as member for old / new ui

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/tests/MyMedia/converted/test_665.py
web/tests/channel/converted/test_724.py

started test 724 - "My Channels - Sort Channels - NOT FINISHED

finished test 726 - My Channels - Filter view  for new / old ui

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/lib/myMedia.py
web/tests/MyMedia/converted/.pytest_cache/v/cache/nodeids
web/tests/MyMedia/converted/test_667.py
web/tests/MyMedia/converted/test_668.py
web/tests/channel/converted/.pytest_cache/v/cache/nodeids
web/tests/channel/converted/test_724.py
web/tests/channel/converted/test_726.py

added new test 677 - My Media - Filter by media Type - NOT FINISHED

fix bugs in channels tests

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/base.py
web/lib/myMedia.py
web/tests/MyMedia/converted/.pytest_cache/v/cache/nodeids
web/tests/MyMedia/converted/test_666.py

started test 666 My Media - Filter by status - NOT FINISHED

finish test 667 My Media - Filter by media Type for old / new ui

---

web/ini/partnerDetails.csv
web/lib/api.py
web/lib/clsCommon.py
web/lib/utilityTestFunc.py

Create/Delete Category via API

NEW!!! API Class

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/entryPage.py
web/lib/enums.py
web/lib/myMedia.py
web/tests/MyMedia/converted/test_669.py
web/tests/channel/converted/test_747.py

added test 747  Channel page - Shared Repository  - NOT FINISHED

added test 669 My Media - View: Collapsed Expanded - FINISHED

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/admin.py
web/lib/channel.py
web/tests/category/converted/test_722.py
web/tests/channel/converted/test_747.py

started test 722 Categories - Browse channels - NOT FINISHED

finished test 747 Channel page - Shared Repository for old/new ui

---

web/ini/testSet.csv
web/tools/csvArranger.py

Csv Arrander - done

---

web/lib/channel.py
web/lib/editEntryPage.py

Schedule set date and time fix

---

web/lib/entryPage.py
web/lib/myMedia.py
web/tests/HomePage/test_1573.py
web/tests/MyMedia/converted/test_667.py

finshhed test filter by media type
finisged test sort
starting test search in my media - NOT FINISHED

finished test filter by status

---

web/lib/freeTrial.py
web/lib/myMedia.py
web/tests/FreeTrial/test_653.py
web/tests/MyMedia/converted/test_665.py

finished test 665 - search in my media

---

web/lib/entryPage.py
web/tests/playlist/converted/test_675.py

Fix test 675 (playlist reorder) - change upload method

Fix for addComment - wait comments module to load

---

web/lib/myPlaylists.py
web/tests/playlist/test_677.py

DeletePlaylist: Add more timeout, wait more for delete button

Test 677: Add GUID to playlists

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/globalSearch.py
web/tests/GlobalSearch/converted/test_637.py

started test 637 Global search - Global Search for Channel

finished test 2510 Global search - Global Search for Category

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/globalSearch.py
web/media/captions/app-caption-entry-page.xml
web/tests/GlobalSearch/converted/test_2510.py
web/tests/GlobalSearch/converted/test_637.py
web/tests/GlobalSearch/converted/test_638.py
web/tests/GlobalSearch/converted/test_639.py

started test 639  Global Search for Captions in Video - NOR FINISHED

finished test 637 - Global Search for Channel

---

web/lib/myPlaylists.py
web/tests/playlist/converted/test_675.py

Refactor method 'shufflePlaylistEntries'

Fix test 675 (playlist reorder)

---

web/ini/testPartnersProd.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/category.py
web/lib/channel.py
web/lib/upload.py
web/tests/MyMedia/converted/test_651.py
web/tests/category/converted/test_716.py
web/tests/channel/converted/test_1395.py

finished test 651 - Navigate to entry page from upload page for old/ new ui
finished test 1395 - channels type for old/new ui

finished test 716 - categories type for old/new ui

---

web/ini/testPartnersProd.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/base.py
web/lib/channel.py
web/lib/login.py
web/tests/channel/converted/test_730.py
web/tests/channel/converted/test_731.py
web/tests/channel/converted/test_738.py
web/tests/collaboration/test_3280.py

finished test 738 - Channel page - Edit metadata - for old/ new ui

finished test 730 - My Channels - Create Channel - for old/ new ui

---

web/ini/testPartnersTestingNewUI.csv
web/lib/channel.py
web/tests/channel/test_1557.py

Fix import channel test
Fix Channel page - Edit Entry link test

Add test 712

---

web/ini/testPartnersProd.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/category.py
web/lib/channel.py
web/tests/category/converted/test_716.py
web/tests/category/converted/test_721.py

working on test 721 - Categories - Import Mermbers not finished

finished test Categories - Members tab for new / old ui

---

web/lib/category.py
web/lib/channel.py
web/lib/editEntryPage.py
web/lib/myMedia.py
web/tests/MyMedia/converted/test_667.py
web/tests/category/converted/test_721.py

finished test 721 Categories - Import Mermbers - for old/ new ui

fix bugs in test 667, 668

---

web/lib/category.py
web/lib/channel.py
web/lib/globalSearch.py
web/lib/myMedia.py
web/tests/GlobalSearch/converted/test_639.py
web/tests/category/converted/test_1025.py
web/tests/channel/converted/test_742.py

continue working on test 1025- not finished

fixed bugs in tests 639, 742

---

web/lib/channel.py
web/lib/enums.py
web/tests/eSearch/perCondition/test_6.py
web/tests/eSearch/test_4311.py

New pre condotion test: test_6.

---

web/ini/testPartnersProd.csv
web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/editEntryPage.py
web/lib/utilityTestFunc.py
web/tests/entryPage/test_644.py
web/tests/kaf/blackBoard/test_589.py
web/tests/kaf/blackBoard/test_590.py
web/tests/kaf/blackBoard/test_591.py
web/tests/kaf/blackBoard/test_593.py
web/tests/kaf/blackBoard/test_604.py

start working on 593 for BB NOT finished

finished tests 604, 589, 590, 591 for BB

---

web/lib/channel.py
web/lib/myPlaylists.py

Embed - click on warning message was removed

Old UI - Fix for add new content to channel button locator

---

web/ini/testPartnersProd.csv
web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/editEntryPage.py
web/lib/myMedia.py
web/tests/editEntryPage/test_695.py
web/tests/kaf/blackBoard/test_589.py
web/tests/kaf/blackBoard/test_590.py
web/tests/kaf/blackBoard/test_591.py
web/tests/kaf/blackBoard/test_593.py
web/tests/kaf/blackBoard/test_597.py

working on test 597 BB My Media - Delete - single - not finished

fix test 660 - kms My Media - Delete - single

---

web/lib/base.py
web/tests/category/converted/test_710.py

Added additional sleep for test 710

Added refresh method to Base madule

---

web/ini/testPartnersTestingNewUI.csv
web/lib/myMedia.py
web/tests/eSearch/perCondition/test_2.py
web/tests/eSearch/test_3901.py
web/tests/eSearch/test_4309.py
web/tests/eSearch/test_4310.py
web/tests/eSearch/test_4311.py
web/tests/eSearch/test_4325.py

Updated verifySortInMyMedia function in My media

Updated tests 2, 3901, 4309, 4310, 4311, 4325 tests.

---

web/lib/category.py
web/lib/channel.py
web/lib/kea.py
web/tests/eSearch/perCondition/test_2.py
web/tests/eSearch/perCondition/test_8.py
web/tests/eSearch/test_3901.py
web/tests/eSearch/test_3902.py

Updated test 2.
Added new pre-condition test: test 8.
Updated tests 3901, 3902.

Updated verifySOrt functions in channel, category and kea.

---

web/lib/upload.py
web/tests/eSearch/perCondition/test_10.py
web/tests/playlist/test_679.py

test_10- eSearch Filter By Owner Pre Conditions- In Process

---

web/lib/admin.py
web/tests/playlist/test_673.py

Fix test 673 (embed playlist) enable secure embed

Admin page - new method: enableSecureEmbed

---

web/lib/channel.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/channel/test_736.py
web/tests/kaf/blackBoard/test_4425.py
web/tests/kaf/blackBoard/test_608.py
web/tests/kaf/blackBoard/test_609.py
web/tests/kaf/blackBoard/test_611.py

test 4425 -BlackBoard: Remove Media From Media Gallery
test 608 - BlackBoard - My Media - Search by Name / Description / Tags
test 609 - BlackBoard: My Media - Sort Media
test 611 - BlackBoard: My Media - Filter by media Type
fix bugs in 665, 667 , 736

added and finished 4 tests for old/new ui:

---

requirements.txt
web/lib/clsTestService.py
web/tests/HomePage/test_643.py

Added requirements for pip install
Fix log - Start Firefox

Fix test 643 new UI, TODO old UI

---

web/ini/partnerDetails.csv
web/lib/clsTestService.py
web/lib/localSettings.py
web/lib/myPlaylists.py
web/tests/HomePage/test_643.py

Add new instance to partnerDetails.csv

---

web/lib/editEntryPage.py
web/lib/entryPage.py

Also use multipleElements=True when using it.

Update locator EDIT_ENTRY_ATTACHMENTS_TAB in entry and edit entry page.

---

web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/category.py
web/lib/channel.py
web/lib/clsCommon.py
web/lib/editEntryPage.py
web/lib/enums.py
web/lib/kafGeneric.py
web/lib/kafMoodle.py
web/lib/localSettings.py
web/lib/logger.py
web/lib/myMedia.py
web/lib/utilityTestFunc.py
web/tests/kaf/moodle/test_2109.py

started test 2109 Moodle - Preview all kinds of media from My Media and Gallery(NOT finished)

adding Kaf Moodle infrastructure

---

web/lib/myMedia.py
web/tests/eSearch/test_4329.py
web/tests/eSearch/test_4331.py
web/tests/eSearch/test_4332.py
web/tests/eSearch/test_4333.py
web/tests/eSearch/test_4334.py

Test 4329,4330 fixed
Test created 4331,4332,4333,4334

New method 'verifyEntryTypeIconAferSearch'

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv

test_2088:KAF BB - Upload From Embed As Standalone
test_4439:eSearch - Search in entry page - Captions
test_4051:eSearch - Search in entry page - Captions
test_4440:eSearch - Search in entry page - Captions
test_4441:eSearch - Search in entry page - Captions
test_4442:eSearch - Search in entry page - Captions
test_4443:eSearch - Search in entry page - Captions
test_4444:eSearch - Search in entry page - Captions
test_4445:eSearch - Search in entry page - Captions

Next tests added to CSV files:

---

web/lib/kafBB.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/kaf/blackBoard/test_109.py
web/tests/kaf/blackBoard/test_113.py
web/tests/kaf/blackBoard/test_2087.py
web/tests/kaf/blackBoard/test_2088.py
web/tests/kaf/moodle/test_2104.py
web/tests/kaf/moodle/test_2105.py

Updated moodle tests 2104, 2105

Updated blackboard tests: 109,113,2087, 2088.

---

web/lib/kafBB.py
web/lib/kafMoodle.py
web/lib/myMedia.py
web/lib/player.py
web/lib/utilityTestFunc.py
web/tests/kaf/moodle/test_2107.py
web/tests/kaf/moodle/test_2108.py
web/tests/kaf/moodle/test_2111.py
web/tests/kaf/moodle/test_2114.py
web/tests/kaf/moodle/test_2127.py

New moodle tests (finished) : 2106, 2107, 2108, 2111, 2114.

---

web/lib/myMedia.py
web/tests/category/converted/test_709.py
web/tests/channel/converted/test_734.py

multipleElements=True for publish from entry page

---

web/lib/enums.py
web/lib/kafGeneric.py
web/lib/kafMoodle.py
web/tests/kaf/blackBoard/test_1648.py
web/tests/kaf/moodle/test_2128.py

Add new test 2128 (not finished)

Upated tests 1648 and 2127 (finished).

---

web/lib/myMedia.py
web/tests/eSearch/test_4337.py
web/tests/eSearch/test_4338.py
web/tests/eSearch/test_4339.py
web/tests/eSearch/test_4340.py
web/tests/eSearch/test_4341.py
web/tests/eSearch/test_4342.py

tests 4337 ,4338 4339, 4340, 4341, 4342

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/kafBB.py
web/lib/kafGeneric.py
web/lib/kafMoodle.py
web/lib/myMedia.py
web/tests/kaf/blackBoard/test_600.py
web/tests/kaf/blackBoard/test_610.py
web/tests/kaf/canvas/test_2281.py
web/tests/kaf/canvas/test_2282.py
web/tests/kaf/canvas/test_2283.py
web/tests/kaf/canvas/test_2285.py
web/tests/kaf/canvas/test_2286.py
web/tests/kaf/canvas/test_2290.py
web/tests/kaf/moodle/test_2117.py

added new tests to canvas : 2281,2282,2283,2285,2286,2290 all finished

fix bug in test 610

---

web/lib/channel.py
web/lib/clsCommon.py
web/lib/entryPage.py
web/lib/enums.py
web/lib/kafD2L.py
web/lib/kafGeneric.py
web/lib/localSettings.py
web/lib/logger.py
web/lib/myMedia.py
web/lib/upload.py
web/lib/utilityTestFunc.py
web/tests/kaf/D2L/test_2543.py

added infrastructure for D2L

---

web/lib/kafGeneric.py
web/lib/kafMoodle.py
web/tests/eSearch/test_4051.py
web/tests/eSearch/test_4347.py
web/tests/eSearch/test_4440.py
web/tests/eSearch/test_4479.py
web/tests/kaf/moodle/test_628.py

New moodle test 628 (not finished)

Updated tests 4051, 4347, 4440, 4479.

---

web/lib/enums.py
web/lib/kea.py
web/lib/player.py
web/tests/kea/Editor/test_4455.py
web/tests/kea/Editor/test_4458.py
web/tests/kea/Editor/test_4465.py
web/tests/kea/Editor/test_4543.py
web/tests/kea/Editor/test_4562.py
web/tests/kea/Editor/test_4621.py
web/tests/kea/Editor/test_4622.py

test 4462 - trim entry with captions and slides - finished - need to add Quiz support

test 4621& 4562 (a.k.a clip & trim entry with cations) - finished

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/lib/kafD2L.py
web/lib/kafGeneric.py
web/tests/channel/converted/test_738.py
web/tests/kaf/D2L/test_2549.py
web/tests/kaf/D2L/test_2550.py
web/tests/kaf/D2L/test_2551.py
web/tests/kaf/D2L/test_2552.py
web/tests/kaf/D2L/test_2556.py

added new test to d2l : 2549, 2550,2551,2552 - All finished
added test 2556 NOT finished

fix test 738

---

web/ini/testSet.csv
web/lib/clsQrCodeReader.py

takeQrCodeSlideScreenshot
takeQrCodeVideoScreenshot

FIX: QR TEST

---

web/lib/channel.py
web/lib/enums.py
web/lib/globalSearch.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/eSearch/test_4508.py
web/tests/eSearch/test_4509.py
web/tests/eSearch/test_4599.py
web/tests/eSearch/test_4603.py
web/tests/eSearch/test_4682.py
web/tests/eSearch/test_4695.py
web/tests/eSearch/test_4696.py
web/tests/eSearch/test_4697.py

Created a new function, switchBetweenMediaAndPendingWithRefresh in channel, in order to increase the performance between the transition
Updated the showAllEntriesPendingTab function from channel, in order to make sure that the function works properly and to increase the performance
Created a new function, extractEntryIDFromCheckBox in upload, in order to be able to extract the entryID while using a search term in Pending tabs
Updated the method_helper_approveEntry, method_helper_rejectEntry, rejectEntriesInPandingTab and approveEntriesInPandingTab in order to support the extractEntryIDFromCheckBox function

Completed all the test cases for "Approve / Reject"

---

web/lib/channel.py
web/lib/editEntryPage.py
web/lib/enums.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/eSearch/perCondition/test_29.py
web/tests/eSearch/perCondition/test_30.py
web/tests/eSearch/perCondition/test_31.py
web/tests/eSearch/perCondition/test_32.py
web/tests/eSearch/perCondition/test_33.py
web/tests/eSearch/perCondition/test_34.py
web/tests/eSearch/test_4563.py
web/tests/eSearch/test_4589.py
web/tests/eSearch/test_4590.py
web/tests/eSearch/test_4591.py
web/tests/eSearch/test_4592.py
web/tests/eSearch/test_4593.py
web/tests/eSearch/test_4594.py
web/tests/eSearch/test_4595.py
web/tests/eSearch/test_4596.py
web/tests/eSearch/test_4705.py
web/tests/eSearch/test_4706.py

Upload the preCondition test for "Filter by Membership"
Updated the preCondition tests for "Filter by Ownership" with a new owner and functions
Created a new preCondition test for "Filter by Ownership" in order to be able to verify entries from the Category Pending tab too
Created a new function, changeMediaOwner, in order to be able to complete the changes for the "Filter by Ownership" preConditions
Updated the publishSingleEntry in order to verify if the entries are list or not, fixing an issue for the entries that were not a list
Created a new function, verifyChannelIsPresent, in order to verify that the desired channels are displayed
Updated the enum file
Updated the pendingBulkRejectAndApprove function in order to show all the pending tab entries

Upload all the test cases for "Filter by Membership"

---

web/lib/myMedia.py
web/tests/eSearch/test_4476.py
web/tests/eSearch/test_4477.py
web/tests/eSearch/test_4615.py
web/tests/eSearch/test_4618.py
web/tests/eSearch/test_4619.py
web/tests/eSearch/test_4726.py

Updated the verifyFilterSection in order to support removeFilterOptionWithXButton
Fixed the following test case: 4476,4477, 4615,4618,4619 and 4726

Implemented a new function, removeFilterOptionWithXButton

---

web/lib/myMedia.py
web/tests/eSearch/test_4476.py
web/tests/eSearch/test_4477.py
web/tests/eSearch/test_4478.py
web/tests/eSearch/test_4479.py
web/tests/eSearch/test_4618.py

Fixed the filterCustomDuration function
Created a new function, filterCustomDurationUsingSidebar

Fixed the following test cases 4571, 4567, 4607, 4611, 4615 and 4618

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/player.py

csv update

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/editEntryPage.py
web/lib/entryPage.py
web/tests/kaf/canvas/test_2298.py
web/tests/kaf/canvas/test_2305.py
web/tests/kaf/canvas/test_2308.py
web/tests/kaf/canvas/test_2335.py
web/tests/kaf/jive/test_2498.py

added and finished 4 tests to canvas : 2298,2305,2308,2335

funushed test 2498 in jive

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/tests/kaf/canvas/test_2292.py
web/tests/kaf/canvas/test_2336.py

addded test 2336 to canvas - finished

---

web/lib/base.py
web/lib/clsPractiTest.py
web/tests_setup/test_night_run.py

Methods Completed:
setStatusToEntireTestset
chunks
createDataChank
TODO: setTestsetAttributes

Create infrastructure for Night Execution

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/clsCommon.py
web/lib/enums.py
web/lib/kafD2L.py
web/lib/kafGeneric.py
web/lib/kafSakai.py
web/lib/localSettings.py
web/lib/logger.py
web/lib/upload.py
web/lib/utilityTestFunc.py
web/tests/kaf/sakai/test_2940.py

fix bug in D2L login function

---

web/lib/clsCommon.py
web/lib/entryPage.py
web/lib/enums.py
web/lib/kea.py
web/lib/player.py
web/tests/kea/Quiz/test_4759.py
web/tests/kea/Quiz/test_4766.py
web/tests/kea/Quiz/test_4767.py
web/tests/kea/Quiz/test_4768.py
web/tests/kea/Quiz/test_4769.py
web/tests/kea/Quiz/test_4772.py
web/tests/kea/Quiz/test_4773.py

Completed the test case #4767 Quiz - Experience section in Entry Page - EnabledCompleted the test case #4772 Quiz - Experience section in Entry Page - Disabled
Completed the test case #4773 Quiz - Experience section in Entry Page - Default
Created a new function, navigateToFirstQuiz, in order to navigate to the first quiz page, if the user is in question screen or if the player plays in background
Created a new function, clickAndSeekOnSlider, in order to select a specific time within the player and verify if "No seeking Forward" option is enabled or disabled
Created a new function, changeQuizAnswer, in order to navigate to the first quiz, and replace an already selected answer with a new one, specified in dictionary
Created a new function, resumeFromBeginingQuiz, in order to verify if the …

Completed the test case #4766 Quiz - Experience section in KEA PAGE

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/editEntryPage.py
web/lib/entryPage.py
web/tests/kaf/sakai/test_2934.py

fix bugs in kms

---

web/lib/channel.py
web/lib/kafD2L.py
web/lib/kafGeneric.py
web/lib/kafJive.py
web/lib/upload.py
web/tests/eSearch/test_4314.py
web/tests/kaf/D2L/test_2906.py
web/tests/kaf/D2L/test_2907.py
web/tests/kaf/jive/test_2512.py

Added new test for jive: 2512 (not finished).
Fix for esearch test 4314

Added new tests to d2l: 2906, 2907, 2908 (finished).

---

web/tests/kaf/sakai/test_2938.py
web/tests/kaf/sakai/test_2939.py
web/tests/kaf/sharePoint/test_2891.py

add new test to Share point 2891 not finished

add new tests to Sakai 2939 and 2938 finished

---

web/lib/entryPage.py
web/lib/kafSharepoint.py

fixed function switchToSharepointIframe

---

web/lib/kafD2L.py
web/lib/kafGeneric.py
web/lib/kafJive.py
web/lib/kafSakai.py
web/lib/upload.py
web/lib/utilityTestFunc.py
web/tests/kaf/jive/test_2509.py
web/tests/kaf/jive/test_2511.py
web/tests/kaf/sakai/test_3044.py

Added new sakai test: 3044 (not finished)

Added new jive tests: 2509, 2511, 2512 (finished).

---

web/lib/channel.py
web/lib/kafSharepoint.py
web/lib/myMedia.py
web/lib/upload.py
web/tests/kaf/sharePoint/test_2885.py

change function showAllEntriesPendingTab

finish test 2885 for sP

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/channel.py
web/lib/myMedia.py
web/tests/kaf/sharePoint/test_2887.py
web/tests/kaf/sharePoint/test_2888.py

added 2 test to SP : 2887, 2888 finished

---

web/tests_setup/test_0000.py

Fix 'pending' with 'run only failed' when no failed test to run

PractiTest script

---

web/lib/enums.py
web/lib/kea.py
web/lib/player.py
web/tests/kea/Quiz/test_4776.py
web/tests/kea/Quiz/test_4786.py
web/tests/kea/Quiz/test_4788.py
web/tests/kea/Quiz/test_4789.py
web/tests/kea/Quiz/test_4790.py
web/tests/kea/Quiz/test_4791.py
web/tests/kea/Quiz/test_4792.py

#4778 Quiz - KEA Quiz Question types - New Quiz with Media Owner
#4786 Quiz - KEA Quiz Question types - Resumed Quiz with Media Owner
#4788 Quiz - KEA Quiz Question types - Submitted Quiz with Media Owner
#4789 Quiz - KEA Quiz Question types - New Quiz with Anonymous User
#4790 Quiz - KEA Quiz Question types - New Quiz after Refresh with Anonymous User
#4791 Quiz - KEA Quiz Question types - Submitted Quiz 0% score with Media Owner
#4792 Quiz - KEA Quiz Question types - Submitted Quiz 50% score with Media Owner
Fixed an issue from verifyQuestionScreenState function, where it failed to verify a selected answer while having the submitted state true
Created a new function, keaTimelineVerification, in order to verify the time stamp, quiz order, total question number and the Quiz Title from KEA …

Created/updated the following test cases:

---

web/lib/entryPage.py

When clicking on add comment button

Add 'multipleElements=True' to addComment method

---

web/lib/player.py
web/tests/kea/Quiz/test_4804.py
web/tests/kea/Quiz/test_4805.py
web/tests/kea/Quiz/test_4806.py
web/tests/kea/Quiz/test_4807.py
web/tests/kea/Quiz/test_4808.py
web/tests/kea/Quiz/test_4809.py
web/tests/kea/Quiz/test_4810.py
web/tests/kea/Quiz/test_4811.py
web/tests/kea/Quiz/test_4812.py
web/tests/kea/Quiz/test_4813.py
web/tests/kea/Quiz/test_4814.py

#4804 Quiz - Submitted Quiz in Channel with Normal User
#4805 Quiz - Submitted Quiz with Media Owner and reopen it with Normal user ( New state for Quiz)
#4806 Quiz - Details Section - Download functionality - Anonymous User in KMS
#4807 Quiz - Answer Quiz (without submitting it) with KMS Anonymous and Refresh
#4808 Quiz - Submitted Quiz for Audio Entry
#4809 Quiz - Resumed Quiz for Audio Entry
#4810 Quiz - New Quiz for Audio Entry
#4811 Quiz - Submitted Quiz for Youtube Entry
#4812 Quiz - Resumed Quiz for Youtube Entry
#4813 Quiz - New Quiz for Youtube Entry
Updated the quizCreation and asnwerQuiz function, in order to proper integrate the removeTouchOverlay function

Completed the following test cases:

---

web/lib/admin.py
web/lib/player.py
web/tests/kea/Quiz/test_4786.py
web/tests/kea/Quiz/test_4788.py
web/tests/kea/Quiz/test_4790.py
web/tests/kea/Quiz/test_4791.py
web/tests/kea/Quiz/test_4792.py
web/tests/kea/Quiz/test_4804.py
web/tests/kea/Quiz/test_4806.py
web/tests/kea/Quiz/test_4807.py
web/tests/kea/Quiz/test_4814.py
web/tests/kea/Quiz/test_4815.py
web/tests/playlist/test_673.py

Updated all the functions inside the quizVerification, in order to verify if the entry is embed and if it has secure embed on / off
Updated the verifySubmittedScreen function, in order to verify Quiz Questions from multiple ‘Submitted’ screens
Updated the metadata from multiple test cases
Completed test case #4814 Quiz - Youtube based entry: Submitted Quiz with many Quiz Questions (15 questions)
Created a new function, enabledSecureEmbed, in order to enable / disable secureEmbed option

Fixed an issue from answerQuiz function

---

web/lib/player.py
web/tests/kea/Quiz/test_4790.py
web/tests/kea/Quiz/test_4816.py
web/tests/kea/Quiz/test_4817.py
web/tests/kea/Quiz/test_4818.py

Updated test case 4815 in order to add proper values for VM
Updated the switchToPlayerIframe function, in order to decrease the timeout
Completed test case #4816, #4817, #4818

Updated test case 4790 in order to add a new step

---

web/lib/login.py
web/lib/player.py
web/tests/kea/Quiz/test_4825.py
web/tests/kea/Quiz/test_4826.py
web/tests/kea/Quiz/test_4827.py
web/tests/kea/Quiz/test_4828.py

Created a new function, loginToKMSEmbed
Fixed an issue from quizVerification function

Completed test case 4825, 4826, 4828, 4828

---

web/lib/enums.py
web/lib/kafBB.py
web/lib/kafGeneric.py
web/tests/kaf/blackBoard/test_1030.py
web/tests/kaf/moodle/test_2122.py

New BB test - 1030 (not finished).

New moodle test - 2122 (finished).

---

web/lib/entryPage.py
web/lib/recscheduling.py
web/tests/Recscheduling/test_4852.py

added more code to recscheduling

fix ENTRY_PAGE_MEDIA_IS_BEING_PROCESSED locator

---

web/lib/kea.py
web/lib/player.py
web/tests/kea/Quiz/test_4854.py
web/tests/kea/Quiz/test_4855.py
web/tests/kea/Quiz/test_4856.py

#4857 Quiz - Timeline section while Using Zoom Option - KEA Page
#4855 Quiz - Submitting Quiz with Answer order changed - Entry Page
Created a new function, verifyZoomLevelInTimeline, in order to:
Verify that the Zoom Level Pointer location is properly changed based on the zoom option state
Verify that the Timeline section is properly increased / decreased, after using the zoom option
Verify that the Question distance is properly increased / decreased, after using the zoom option
Fixed an issue from verifySubmittedScreen, where a condition was incomplete
Fixed an issue from quizVerificationMethodHelper, where it thrown an exception while 'Hint' value was not provided

Completed multiple test cases:

---

web/lib/entryPage.py
web/lib/kafBB.py
web/lib/kafCanvas.py
web/lib/utilityTestFunc.py
web/tests/kaf/blackBoard/test_1030.py
web/tests/kaf/canvas/test_4856.py

Canvas test - 4856 (not finished)

BB test - 1030 (finished).

---

web/lib/entryPage.py
web/tests/eSearch/perCondition/test_13.py
web/tests/eSearch/perCondition/test_30.py
web/tests/kea/Quiz/test_4814.py
web/tests/kea/Quiz/test_4853.py

Fixed test case #13, #30, #4814, #4853

Fixed getEmbedLink function

---

web/lib/channel.py
web/lib/myMedia.py

Incresead showAllEntriesInChannelCategoryPage timeout

Updated ENTRY_NO_MEDIA_FOUND_MESSAGE locator with a new condition

---

web/lib/clsTestService.py
web/tests/kea/Quiz/test_4806.py

Create temp download folder before driver.remote creation

Revert test 4806

---

web/lib/channel.py
web/lib/clsCommon.py
web/lib/enums.py
web/lib/kafBBUltra.py
web/lib/kafGeneric.py
web/lib/localSettings.py
web/lib/logger.py
web/lib/upload.py
web/lib/utilityTestFunc.py
web/tests/kaf/BBUltra/test_4872.py

add infrastructure to blackboard ultra
started new test for blackboard ultra  4872 - NOT finished

fix bugs in moodle

---

web/tests/kaf/BBUltra/test_4859.py
web/tests/kaf/BBUltra/test_4860.py
web/tests/kaf/BBUltra/test_4863.py
web/tests/kaf/BBUltra/test_4871.py
web/tests/kaf/BBUltra/test_4872.py
web/tests/kaf/BBUltra/test_4876.py

test_4859 done
4860 not finished
4863 not finished
4871 done
4872 done
4876 done

adding new tests for BB ultra

---

web/lib/base.py
web/lib/login.py
web/lib/recscheduling.py
web/tests/Recscheduling/test_4852.py

fix 'navigate to login'  function

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv

Massive CSV udpdate

---

web/lib/kafD2L.py
web/lib/kafMoodle.py
web/lib/utilityTestFunc.py
web/tests/kaf/D2L/test_4957.py

New D2L test 4957 (not finished)

New Moodle test 826 (finished)

---

web/lib/enums.py
web/lib/localSettings.py
web/lib/recscheduling.py
web/lib/utilityTestFunc.py
web/tests/Recscheduling/test_4852.py
web/tests/kaf/moodle/test_826.py

finished test setEventRecurrence

aaded url for kaf sp - one for testing and one for production

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/tests/channelPlaylist/test_4293.py

Update csv fiels

---

web/lib/admin.py
web/lib/base.py
web/lib/channel.py
web/lib/kafD2L.py
web/lib/logger.py
web/lib/myMedia.py
web/tests/channelPlaylist/test_4292.py
web/tests/channelPlaylist/test_4293.py

fix locators in D2L
fix test 4292 - all done
test 4293 - not done (oded is working on it)

added fix for log deleteing

---

web/lib/editEntryPage.py
web/lib/myMedia.py
web/tests/entitlements/test_4984.py

Updated #4983 test case in order to workaround an issue
Completed test case #4984

Increased showAllEntrie timeout

---

web/lib/channel.py
web/tests/channelPlaylist/test_4293.py
web/tests/kaf/BBUltra/test_4883.py

4293 finished embed channe playlist

---

web/lib/kea.py
web/lib/player.py
web/tests/entitlements/test_4983.py

Updated answerQuiz function in order to fix an issue and update the signature
Fixed test case 4983

Updated quizCreation function in order to make it more reliable

---

web/lib/kea.py
web/lib/player.py
web/lib/upload.py

Updated saveKeaChanges function in order to make it more reliable

Fixed answerQuiz function

---

web/lib/kea.py

Updated changeHotspotLocation and hotspotToolTipVerification with new signature names

Fixed quizCreation for D2L application

---

web/lib/clsCommon.py
web/lib/entryPage.py
web/lib/enums.py
web/lib/quizAnalytics.py
web/tests/kaf/D2L/test_4957.py
web/tests/kea/Quiz/test_5111.py

Updated test 4957. New test 5111 (not finished)

New class for quiz analytics (quizAnalytics).

---

web/lib/kafBBUltra.py
web/lib/utilityTestFunc.py
web/tests/kaf/BBUltra/test_4864.py
web/tests/kaf/BBUltra/test_4870.py
web/tests/kaf/BBUltra/test_4878.py

Tests for 4878,4864 done

---

web/lib/kafBB.py
web/lib/kafMoodle.py
web/lib/player.py
web/lib/quizAnalytics.py
web/tests/kea/Quiz/test_5105.py
web/tests/kea/Quiz/test_5116.py

Updated 5105.
New test 5116 (not finished)

Updated BB and moodle for KAF's tests.

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/kea.py

Updated quizCreation function in order to support D2L application

Updated the CSVs file with new Hotspot and Editor test cases

---

web/lib/base.py
web/lib/recscheduling.py
web/tests/category/converted/test_710.py

added the option to work with css locator to base

---

web/lib/channel.py
web/lib/enums.py
web/lib/globalSearch.py
web/tests/channelPlaylist/test_4293.py
web/tests/entitlements/test_5012.py
web/tests/entitlements/test_5028.py
web/tests/entitlements/test_5125.py
web/tests/entitlements/test_5127.py
web/tests/kea/Editor/test_4913.py
web/tests/kea/Editor/test_4955.py

#5125 Entitlements - Public Opened Channel using Global Page
#5127 Entitlements - Public Opened Channel using Channels Page and Anonymous Users ON
Updated the addMembersToChannel, deleteChannel functions in order to make them more reliable
Updated the Public entitlement test cases in order to reflect the new Public Privacy Type - (Open and Restricted)
Updated the ChannelPrivacyType enum class in order to support the new Public Privacy Type
Updated the selectChannelPrivacy function in order to support the new Public Privacy Type

Completed two new Entitlement test cases:

---

web/lib/editEntryPage.py
web/lib/upload.py
web/tests/kea/Editor/test_4913.py
web/tests/kea/Editor/test_4955.py

Increased default number of retries from 4 to 5 in uploadEntry
Updated test 4913 and 4955 in order to make them more reliable

Fixed uploadSlidesDeck when using waitToFinish = False

---

web/lib/recscheduling.py
web/tests/Recscheduling/test_4970.py

fix and added functions in recsheduling

working on test 4970 - not finish

---

web/lib/recscheduling.py
web/tests/Recscheduling/test_4970.py

added more functions to recshceduling

stil working on test 4970

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/recscheduling.py
web/tests/Recscheduling/test_4970.py

added more function to recschesduling
update csv

still working on test 4970

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTesting.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/kea.py
web/lib/upload.py

Fixed an exception error from hotspotTimelineVerification function

Fixed #5141 in the CSVs file

---

web/lib/quizAnalytics.py
web/tests/kea/Quiz/test_5131.py
web/tests/kea/Quiz/test_5135.py

Fix for 5131.

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/player.py
web/lib/quizAnalytics.py
web/tests/kea/Quiz/test_5136.py
web/tests/kea/Quiz/test_5137.py

New tests 5135, 5136 (finished) and 5137 (not finished).

---

web/lib/enums.py
web/lib/quizAnalytics.py
web/tests/kea/Quiz/test_5155.py

Update test 5137.

---

web/lib/entryPage.py
web/lib/quizAnalytics.py
web/tests/kea/Quiz/test_5116.py
web/tests/kea/Quiz/test_5117.py
web/tests/kea/Quiz/test_5137.py
web/tests/kea/Quiz/test_5138.py
web/tests/kea/Quiz/test_5153.py
web/tests/kea/Quiz/test_5154.py
web/tests/kea/Quiz/test_5157.py

New IVQ tests 5153, 5154 abd 5157 (finished).

---

web/lib/kafBBUltra.py
web/lib/kafGeneric.py
web/lib/utilityTestFunc.py
web/tests/kaf/BBUltra/test_4877.py
web/tests/kaf/BBUltra/test_4884.py
web/tests/kaf/BBUltra/test_5156.py

test 4887 not finished
test 4884 done

Ultra 5156 gradebook not finished

---

web/lib/recscheduling.py
web/tests/Recscheduling/test_4971.py
web/tests/Recscheduling/test_5162.py

added but not finished test 4971 - Recscheduling -  Edit an event series

added and finished test 5162 - Recscheduling - Delete Event Series

---

web/ini/testPartnersTestingNewUI.csv
web/tests/kea/Quiz/test_5160.py
web/tests/kea/Quiz/test_5161.py
web/tests/kea/Quiz/test_5163.py
web/tests/kea/Quiz/test_5164.py

fix for 5160, 5161, 5163, 5164

Updating CSV  - testPartnersTestingNewUI.

---

web/lib/clsCommon.py
web/tests/kea/Quiz/test_5159.py
web/tests/kea/Quiz/test_5160.py
web/tests/kea/Quiz/test_5163.py
web/tests/kea/Quiz/test_5164.py

Updated compareBetween2CsvFiles function.

Updated path lines in 5159, 5160, 5163, 5164.

---

web/lib/kafBBUltra.py
web/lib/kafGeneric.py
web/lib/myMedia.py
web/lib/utilityTestFunc.py
web/tests/kaf/BBUltra/test_4877.py
web/tests/kaf/BBUltra/test_5156.py

test 5156 gradebook in progress

test 4877 done

---

web/lib/kea.py
web/lib/player.py
web/tests/kea/Editor/test_4913.py
web/tests/kea/Editor/test_4955.py

Updated the collectQrOfSlidesFromPlayer function, in order to proper take the captions from a quiz entry and add the option to resume from the beginning the entry
Updated the hotspotVerification function, in order to support new coordinates for the center location

Updated the #4913 and #4955 test case in order to workaround a KMS issue

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/recscheduling.py
web/tests/Recscheduling/test_4969.py

started test 4969 - not finished

finished test 4971

---

web/lib/clsCommon.py
web/lib/entryPage.py
web/lib/reach.py
web/tests/kea/Quiz/test_5164.py

New reach class

---

web/lib/entryPage.py
web/tests/kaf/moodle/test_2397.py
web/tests/kaf/moodle/test_628.py
web/tests/reach/test_5178.py

New reach test 5178 (not finished)

---

web/lib/kea.py
web/lib/player.py

Updated launchKEATab function, in order to make it more reliable when navigating to the entry

Fixed hotspotVerification function, where it may remained stuck

---

web/lib/channel.py
web/lib/entryPage.py
web/lib/reach.py
web/tests/reach/test_5178.py

Updated 5178 test (not finished).

---

web/ini/testPartnersProdNewUI.csv
web/ini/testPartnersTestingNewUI.csv
web/ini/testSet.csv
web/lib/recscheduling.py
web/tests/Recscheduling/test_4968.py

started and finished test 4968

---

web/lib/kafD2L.py
web/lib/kea.py
web/tests/kea/Hotspots/test_4956.py

Updated the hotspotToolTipVerification function, in order to support both FF and Chrome
Updated the createGradebook function, in order to support bse environmnet selection

Updated the hotspotCreation function, in order to make it more reliable

---

web/ini/kms/testPartnersProdNewUI.csv
web/ini/kms/testPartnersTestingNewUI.csv
web/ini/kms/testSet.csv
web/lib/recscheduling.py
web/tests/Recscheduling/test_4963.py
web/tests/Recscheduling/test_4964.py
web/tests/Recscheduling/test_4969.py
web/tests/Recscheduling/test_4971.py
web/tests/Recscheduling/test_4972.py
web/tests/Recscheduling/test_5162.py

started test 4964 - NOT finished
update csv

started and finished tesf 4963

---

web/lib/editEntryPage.py
web/tests/editEntryPage/entryDesign/test_5205.py
web/tests/editEntryPage/entryDesign/test_5472.py
web/tests/editEntryPage/entryDesign/test_5475.py
web/tests/editEntryPage/entryDesign/test_5476.py

#5475 Entry Design - Change the Theme and then Reset To Default
#5476 Entry Design - Create custom Theme
Created a new function, changeToDefaultEntryDisplay, in order to have the Entry Design to the default values
Updated the changeEntryDisplay function, in order to support no background color selection

Completed the following Entry Design test cases:
